spring.application.name=reverique
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

mail.smtp.host=${SMTP_HOST}
mail.smtp.port=${SMTP_PORT}
mail.smtp.username=${SMTP_USERNAME}
mail.smtp.password=${SMTP_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}